name: Veracode Static Analysis Pipeline Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '34 3 * * 1'

permissions:
  contents: read

jobs:
  build-and-pipeline-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: zip -r veracode-scan-target.zip ./

      - run: curl --silent --show-error --fail -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      - run: unzip -o pipeline-scan-LATEST.zip

      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'

      - name: Run Veracode Pipeline Scan
        run: |
          java -jar pipeline-scan.jar \
          --veracode_api_id "${{ secrets.VERACODE_API_ID }}" \
          --veracode_api_key "${{ secrets.VERACODE_API_KEY }}" \
          --fail_on_severity="Very High, High" \
          --file veracode-scan-target.zip \
          --json_output results.json
        continue-on-error: true

      - name: Show working directory content after scan
        run: ls -la

      - name: Find results.json file
        run: find . -name "results.json"

      - name: Convert pipeline scan output to SARIF format
        id: convert
        uses: veracode/veracode-pipeline-scan-results-to-sarif@ff08ae5b45d5384cb4679932f184c013d34da9be
        with:
          pipeline-results-json: results.json

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: veracode-results.sarif
